import type { NextPage } from 'next';
import Head from 'next/head';
import { LoginForm, LogoutCta, ValidationForm } from '../components';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  const user = trpc.useQuery(['user.me']);
  return (
    <>
      <Head>
        <title>KAPP</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container mx-auto flex flex-col items-center justify-center min-h-screen p-4'>
        {user.data ? (
          [user.data.id, user.data.validated].join(', validated: ')
        ) : (
          <div>nema</div>
        )}
        <br />
        <div className='flex flex-col items-start gap-5'>
          <h3>
            Login:
            <LoginForm />
          </h3>
          <h3>
            Login:
            <ValidationForm />
          </h3>
          <div className='self-end'>
            <LogoutCta />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
